### ISSUE TITLE
Value Error: numpy.ndarray size changed

### ISSUE THREAD

**Issue by antho214** [FLClab/pySTED#23]
When installing `pySTED` in an already existing environment we run into issues of binary incompatibility of the compiled versions of the C modules.

```bash
Traceback (most recent call last):
  File "run.py", line 18, in <module>
    from pysted import base
  File "pySTED/pysted/base.py", line 93, in <module>
    from pysted import utils, cUtils, raster, bleach_funcs
  File "pySTED/pysted/utils.py", line 23, in <module>
    from pysted import temporal, raster
  File "pysted/raster.pyx", line 2, in init pysted.raster
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
```

**Comment by antho214** [comment]
I could solve the issue by uninstalling `numpy` from the environment and re-installing `pySTED`.
